default[:monasca_notification][:user] = 'monasca-notification'
default[:monasca_notification][:group] = 'monasca-notification'
default[:monasca_notification][:conf_dir] = '/etc/monasca'
default[:monasca_notification][:log_dir] = '/var/log/monasca'
default[:monasca_notification][:data_bag] = 'monasca_notification'
